### ISSUE TITLE
[Bug] cdc table sync with Hive Catalog caseSensitive incorrect

### ISSUE THREAD

**Issue by gfunc** [apache/incubator-paimon#2481]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master branch f68743c1bf429db4b28fccd3e24e23bf0a5266f6

### Compute Engine

flink

### Minimal reproduce step

Run a `KafkaSyncTableAction`  test with a hive catalog. 

### What doesn't meet your expectations?

parser created with `caseSensitive`  hard coded to true, not according to the provided catalog's `caseSensitive()` implementation

https://github.com/apache/incubator-paimon/blob/f68743c1bf429db4b28fccd3e24e23bf0a5266f6/paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/MessageQueueSchemaUtils.java#L53

This will cause case validations to fail due to inconsistency since the hive catalog's `caseSensitive()` would return false.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
In latest master branch (c9ef5202),  the following line will handle the case-sensetivity: https://github.com/apache/incubator-paimon/blob/c9ef52026c366b90c539d01a3da909ea3900b154/paimon-flink/paimon-flink-cdc/src/main/java/org/apache/paimon/flink/action/cdc/SyncTableActionBase.java#L101 

The modification is from 2c401acb. It reorganized the building flow: first we retrieve schema without `caseSensitive`; then we build Paimon table schema with caseSensitive. Ant We also add many tests with case-insensitive catalog in that PR. So I think this bug is solved.

**Comment by gfunc** [comment]
Tested OK with SASL enabled kafka and Hive catalog.
