### ISSUE TITLE
[hotfix] add column `already exists` and `does not exist` exception type

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-paimon#900]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

At present, the columns `already exists` and `does not exist` abnormal printing information are as follows:

![image](https://user-images.githubusercontent.com/37063904/231715023-020b95df-1dae-4092-b628-e20a3387b825.png)

![image](https://user-images.githubusercontent.com/37063904/231715068-b1cdc096-3856-42db-9791-32fdf9ca8b01.png)

### Solution

add column `already exists` and `does not exist` exception type

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tsreaper** [comment]
PR #902 is not a valid solution because it assumes that each `tableRoot` in the `SchemaManager` stands for a table in a catalog. However we also support table outside of catalog (for example, `'connector' = 'paimon'` in Flink), also a lot of tests create `SchemaManager` with an arbitrary path which only holds a test table. These test tables also don't have catalogs and databases.

**Comment by zhuangchong** [comment]
@tsreaper Thanks.

In the SchemaManager class, only the table name is used when printing column`already exists` and `does not exist`. Do you have any suggestions for this method?

Print the column `already exists` and `does not exist` exception:
org.apache.parmin.Catalog$ColumnNotExistException: Column non_existing_col does not exist in the test_table table.

Original exception: 
java.lang.IllegalArgumentException: The column [non_existing_col] doesn't exist in the table[file:/var/folders/r7/v8n4bv9n4cx_gjbffcws50yc0000gn/T/junit5628841770933124332/test_db.db/test_table]
